### ISSUE TITLE
harfbuzz library

### ISSUE THREAD

**Issue by walkero-gr** [AmigaLabs/webkitty#24]
Repo is at https://github.com/harfbuzz/harfbuzz

**Comment by walkero-gr** [comment]
Done by afxgroup for his new clib2

**Comment by 3246251196** [comment]
I guess @afxgroup added this library to his apt repo?

**Comment by afxgroup** [comment]
I need to recompile some other libraries for clib4.. you wanted a new name?? :D and now this is the result..
