### ISSUE TITLE
Latest Cairo port

### ISSUE THREAD

**Issue by walkero-gr** [AmigaLabs/webkitty#9]
We need to have newlib and clib2 libraries for Cairo
We can build them by using the code from 
https://github.com/salass00/cairo_lib

**Comment by kas1e** [comment]
@walkero-gr 
Latest version of Cairo already comes with SDK for Odyssey, and it include some bug-fixes without which you will crash on rendering.

**Comment by walkero-gr** [comment]
@kas1e Thank you for your comments.
Right now we use the ones from Odyssey. Did you update them to latest versions from salass00's repo?

**Comment by kas1e** [comment]
@walkero 
As far as i remember : yes, it is the Fredrick's port + a fix taken from the Cairo main code base.  Anyway, it  not so matter if it latest version of Cairo or not : even old one will render all fine, so you can at least for now use my one from odysseys's SDK: you can be sure that it works, and can render things. Basically you for a start can use everything you need from Odyssey's SDK , as they proved to be working already, so you can at begining save the time and use them, and when webkit port ready and works, can update anything to the latest versions if there will be needs at all

**Comment by walkero-gr** [comment]
@kas1e Thank you for your comments here. That's what we do so far, but since we work with both newlib and afxgroup's clib2 we need to compile it again. So, I think it makes sense to try that with Fredrick's latest version.

**Comment by walkero-gr** [comment]
Done by afxgroup for his new clib2
